[project]
name = "nodc_bvol"
version = "0.1.0"
description = "Handling translations with nomp list etc."
authors = [
    {name = "Magnus Wenzer", email = "magnus.wenzer@smhi.se"},
]
dependencies = [
    "requests>=2.31.0",
    "polars>=1.26.0",
    "numpy>=2.2.5",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
mypkg = ["."]


[tool.ruff]
line-length = 90
indent-width = 4
target-version = "py311"

[tool.ruff.lint]
select = [
    "A",  # flake8-builtins
    "F",  # pyflakes
    "E", # pycodestyle: error
    "W",  # pycodestyle: warning
    "I",  # isort: unsorted-imports
    "RUF"  # Ruff-specific rules
]


[dependency-groups]
dev = [
    "ruff>=0.14.9",
]
